### ISSUE TITLE
How can I implement TinyMPC into Crazyflie 2.1 ?

### ISSUE THREAD

**Issue by emrecintas** [TinyMPC/TinyMPC#20]
How can I implement TinyMPC into Crazyflie 2.1 ? Thanks,

**Comment by xkhainguyen** [comment]
Hey,

Please take a look at https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware,
or more specifically https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/tree/demos/socp/examples.
We've been using this integrated firmware for all Crazyflie experiments. Let me know if you have any specific questions.

**Comment by emrecintas** [comment]
I did the building and flashing process for "tinympc-crazyflie-firmware" as you specified. However, how can I perform the 'eight tracking' and 'hovering' tests you mentioned in your article "TinyMPC: Model-Predictive Control on Resource-Constrained Microcontrollers" on Crazyflie 2.1 with TinyMPC?

**Comment by xkhainguyen** [comment]
We assign MPC as controller 5 (out-of-tree) and you generally have to start it from a high-level commander (cfclient/cflib/[crazyswarm](https://github.com/sschoedel/crazyswarm/blob/khai/ros_ws/src/crazyswarm/scripts/tiny_track_pos.py)).

This previous branch has the figure-8 tracking test you saw in the paper (500 Hz full model): https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/blob/khai/tracking/examples/controller_tinympc_eigen/src/controller_tinympc.cpp

For hovering, you can just set `en_traj` False and send a setpoint from HL commander.

You can do similar things in the `main` branch (https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/tree/main/examples/controller_tinympc_state_soc/src) which is cleaner but slower (50 Hz reduced model) since this is for the SOCP problems (check our second paper). Then of course you can modify it to match the previous test.

If you want, please send an email, we can walk you through the code. Hope it helps.

**Comment by emrecintas** [comment]
Dear Khai Nguyen,

I am writing to you based on your reply below regarding the integration of
tinympc into crazyflie 2.1.

I did all the steps as you wrote and first I run the hover_swarm.launch
file. Afterwards, I run the tiny_track_pos.py file. However, my Crazyflie
drone immediately topples over while taking off. The same thing happens in
the hello_world.py file. I correct the Mass from 0.032 to 0.027 but it
still doesn't work. When you set the Estimator value to 1, it seems to take
off a little, but it doesn't work completely. Some parameters are as
follows:

-estimator: 2
-en_traj: False
-motion_capture_type: "none"



*Your previous answer:*









*"We assign MPC as controller 5 (out-of-tree) and you generally have to
start it from a high-level commander (cfclient/cflib/crazyswarm).This
previous branch has the figure-8 tracking test you saw in the paper (500 Hz
full model):
https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/blob/khai/tracking/examples/controller_tinympc_eigen/src/
<https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/blob/khai/tracking/examples/controller_tinympc_eigen/src/>
controller_tinympc.cppFor hovering, you can just set en_traj False and send
a setpoint from HL commander.You can do similar things in the main branch
(https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/tree/main/examples/controller_tinympc_state_soc/src
<https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/tree/main/examples/controller_tinympc_state_soc/src>)
which is cleaner but slower (50 Hz reduced model) since this is for the
SOCP problems (check our second paper). Then of course you can modify it to
match the previous test.If you want, please send an email, we can walk you
through the code. Hope it helps."*

Khai Nguyen ***@***.***>, 9 Nis 2024 Sal, 19:08 tarihinde
şunu yazdı:

**Comment by XuYue280** [comment]
Hi, I would like to ask after flashing the firmware: example/controller_tinympc_eigen to crazyflie 2.1, do we need to run another python script that containing HL commander instruction (such as takeoff() or goTo()) to achieve the automatic flight?

Thanks.

**Comment by xkhainguyen** [comment]
Yes, please take a look at this script for example
[https://github.com/sschoedel/crazyswarm/blob/khai/ros_ws/src/crazyswarm/scripts/tiny_track_pos.py](https://github.com/sschoedel/crazyswarm/blob/khai/ros_ws/src/crazyswarm/scripts/tiny_track_pos.py)
